### ISSUE TITLE
Ideea

### ISSUE THREAD

**Issue by ghost** [Stefan4189Group/Stefan4189Group.github.io#4]
How about to change from Stefan4189 website to Gamerboi Website or Sean website?

**Comment by Gunful** [comment]
Hello Stefan4189,
We discontinued the project and moved to [The Zerber Project](https://zerberdev.github.io/main).

**Comment by ghost** [comment]
But why not delete this then?

**Comment by Gunful** [comment]
Hello Stefan4189,
We discontinued this project and moved to [The Zerber Project](https://zerberdev.github.io) and not using this website, we want people to easily make websites with this template.

Please continue chatting about this question topic inside the [Discord Server](https://discord.gg/rftYtttu) (1 day temp invite).

**Comment by ghost** [comment]
Ye,but why this still exists if no longer used?

Cheers, Stefan
________________________________

**Comment by Gunful** [comment]
Please answer this in the Discord Server.
[https://discord.gg/r8zF3eQ4uP](https://discord.gg/r8zF3eQ4uP)
